### ISSUE TITLE
.packlist and files() out of sync with symlinks

### ISSUE THREAD

**Issue by zachthompson** [skaji/Distribution-Metadata#6]
With a distribution installed into symlink'ed directory, the physical .packlist and what is returned by Distribution::Metadata::files() is out of sync (due to [Cwd::abs_path()](https://github.com/shoichikaji/Distribution-Metadata/blob/master/lib/Distribution/Metadata.pm#L235)):
- .packlist: /usr/local/perl5/lib/perl5/YAML.pm
- files(): /mnt/md0/usr/local/perl5/lib/perl5/YAML.pm

**Comment by skaji** [comment]
This is intentional.
Do you have any problems?

**Comment by zachthompson** [comment]
Not a problem really as I can always read the .packlist directly.  However, in the docs it says

> my $files = $info->files
> 
>    file paths which is listed in .packlist file

which isn't exactly the case.

**Comment by skaji** [comment]
OK, I documented that in https://github.com/shoichikaji/Distribution-Metadata/commit/08c2558b1a8891fa1783f45a3fffcfab16c3f15

**Comment by skaji** [comment]
released https://metacpan.org/release/SKAJI/Distribution-Metadata-0.05
@zachthompson thanks!
